-- =============================================================================
-- TuSalud Backend - Esquema de base de datos
-- =============================================================================
-- El esquema oficial está en el directorio raíz del monorepo:
--
--   ../database/tusalud_schema_mysql.sql   (MySQL 8+)
--   ../database/tusalud_schema.sql         (PostgreSQL)
--
-- Crear la base y cargar el esquema (MySQL, en el servidor):
--
--   sudo mysql -e "CREATE DATABASE IF NOT EXISTS tusalud;"
--   sudo mysql tusalud < /ruta/completa/database/tusalud_schema_mysql.sql
--
-- Este archivo se mantiene como referencia; no ejecutar como script completo.
-- =============================================================================
