-- Añadir valor CANCELADO al ENUM estado de pedidos (para cancelar pedidos desde la lista).
ALTER TABLE pedidos
  MODIFY COLUMN estado ENUM(
    'PENDIENTE','LISTO_PARA_COTIZACION','FALTA_APROBAR_COTIZACION',
    'COTIZACION_APROBADA','FALTA_PAGO_FACTURA','COTIZACION_RECHAZADA',
    'FACTURADO','COMPLETADO','CANCELADO'
  ) NOT NULL DEFAULT 'PENDIENTE';
