-- Añadir estado "A la espera de cotización" (el vendedor debe adjuntar la cotización).
ALTER TABLE pedidos
  MODIFY COLUMN estado ENUM(
    'PENDIENTE','ESPERA_COTIZACION','LISTO_PARA_COTIZACION','FALTA_APROBAR_COTIZACION',
    'COTIZACION_APROBADA','FALTA_PAGO_FACTURA','COTIZACION_RECHAZADA',
    'FACTURADO','COMPLETADO','CANCELADO'
  ) NOT NULL DEFAULT 'ESPERA_COTIZACION';
